# Generated by Django 3.1.6 on 2022-04-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webuysell_app', '0003_product_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, to='webuysell_app.User'),
        ),
    ]
